### ISSUE TITLE
disqus 无法开启

### ISSUE THREAD

**Issue by zemora** [raytaylorlin/hexo-theme-raytaylorism#102]
我在配置文件中的 `disqus_shortname` 中设置好站点的 shortname 后，仍然显示

    We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

我确认自己的 shortname 填写无误，请问是什么原因？

**Comment by raytaylorlin** [comment]
有可能被墙了。。。试试科学上网吧。。。
