### ISSUE TITLE
数学公式的支持

### ISSUE THREAD

**Issue by sivanWu0222** [raytaylorlin/hexo-theme-raytaylorism#106]
看到博客主题配置文件中，有一个mathjax的配置，修改了true之后，自己书写了数学公式，但是不能够支持！比如mathjax的语法：\sqrt[x]{y}

**Comment by neozhaoliang** [comment]
这套模板是没有问题的，问题可能出在你自己的配置上。你是所有数学公式都不能显示吗？有网页链接可以看看吗？

**Comment by raytaylorlin** [comment]
请在md中这样书写数学公式试试（即公式前后加一个美元符$）：
`$\sqrt[x]{y}$`
