### ISSUE TITLE
在文章和摘要中显示作者名称

### ISSUE THREAD

**Issue by neozhaoliang** [raytaylorlin/hexo-theme-raytaylorism#107]
我在使用您的模板中遇到一个问题：我需要搭建一个团队协作写作的博客，需要在md的开头加上 `author: xxx` 这样一项，然后文章的标题下方，以及首页每篇文章摘要中也出现作者名称，请问应该怎么修改？

**Comment by raytaylorlin** [comment]
根据Hexo的文档[https://hexo.io/zh-cn/docs/writing.html](https://hexo.io/zh-cn/docs/writing.html)，似乎并不支持author参数。

可能只能让你的团队成员在写作的时候强行在md正文内自行加上`作者：XXX`了
