### ISSUE TITLE
多说评论没有同步原来的评论

### ISSUE THREAD

**Issue by zekunyan** [raytaylorlin/hexo-theme-raytaylorism#11]
换了主题以后，原来的评论不见了=。=

**Comment by zekunyan** [comment]
![image](http://ww2.sinaimg.cn/large/0060lm7Tgw1f23gzqsk3tj31320jqabi.jpg)

难道必须先deploy？

**Comment by raytaylorlin** [comment]
[ae9adc0](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/d02533f8e29c688adc42c75012f544bd3ae9adc0)已修复
