### ISSUE TITLE
reading页，显示404怎么办？需要在配置文件中添加什么参数吗？

### ISSUE THREAD

**Issue by Zeroxus** [raytaylorlin/hexo-theme-raytaylorism#12]

**Comment by raytaylorlin** [comment]
需要创建一个reading页面的layout，即**复制`yourblog/themes/raytaylorism/_md/reading`文件夹到`yourblog/source`目录下**，这个是我README文档写漏了，现已补上

**Comment by Zeroxus** [comment]
thanks!
