### ISSUE TITLE
[i18n] _config.yml 設定 language 為 zh-tw 但顯示還是 zh-ch 

### ISSUE THREAD

**Issue by mouson** [raytaylorlin/hexo-theme-raytaylorism#13]
_config.yml 設定 language 為 zh-tw 但顯示還是 zh-ch

**Comment by raytaylorlin** [comment]
不好意思，目前暂不支持繁体中文，后续会逐步加上

**Comment by mouson** [comment]
很喜歡您做的這個 theme ，本來打算自己動手，並且給您發個 PR ，但考量可能會跟您這邊的結構有衝突，我就先不動手了。屆時有需要協助翻譯的部分，我可以再幫忙。

**Comment by raytaylorlin** [comment]
[b2d51d6](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/b2d51d67b5f1ca26d7cce52bd87ce007a86b9bdb) 已新增对繁体中文的支持，能否帮我测试并修改？欢迎给PR，谢谢

**Comment by mouson** [comment]
感謝您。目前看起來翻譯的部份都沒問題了。

**Comment by raytaylorlin** [comment]
好的，如果发现有什么不妥或者翻译遗漏的麻烦给我PR哈：）
