### ISSUE TITLE
標籤頁及分類頁的標題網址錯誤

### ISSUE THREAD

**Issue by mouson** [raytaylorlin/hexo-theme-raytaylorism#14]
以 tag php 來舉例，網址應為 https://{domain.com}/tags/php
但點進該網址後，php 這個標籤上的網址顯示為 https://{domain.com}/tags/php/tags/php/  
因此點進入後，會發生 404 Error

![screenshot 2016-03-30_00-37-50](https://cloud.githubusercontent.com/assets/858588/14115933/e8e82b52-f60f-11e5-865c-9bbf730793d7.png)

**Comment by raytaylorlin** [comment]
能否给个线上链接以及`hexo version`的结果看看？
我怀疑可能是旧版Hexo的bug？我这边的tags没有问题。。。试试更新下Hexo本身

**Comment by mouson** [comment]
hexo version

> hexo: 3.2.0
> hexo-cli: 1.0.1
> os: Darwin 15.4.0 darwin x64
> http_parser: 2.5.2
> node: 4.3.2
> v8: 4.5.103.35
> uv: 1.8.0
> zlib: 1.2.8
> ares: 1.10.1-DEV
> icu: 56.1
> modules: 46
> openssl: 1.0.2g

目前在這邊使用：https://usedfire.net/

再麻煩您幫忙確認。如果還有缺什麼資訊，在麻煩您告知。

**Comment by raytaylorlin** [comment]
不好意思我一开始理解错你的意思了，确实是bug，现已修复，麻烦pull一下

**Comment by mouson** [comment]
感謝您。確認已經修復。
