### ISSUE TITLE
如何将网页改为英文版？

### ISSUE THREAD

**Issue by obserthinker** [raytaylorlin/hexo-theme-raytaylorism#15]
请问如何将模板中的“首页”、“分类”等标签的语言改为英文？

**Comment by raytaylorlin** [comment]
`yourblog/_config.yml`中设置
```
language: en
```

**Comment by obserthinker** [comment]
谢谢。之前不知道为何设置为en后还是繁体中文。不过现在没有问题了。

**Comment by raytaylorlin** [comment]
对英文和繁体中文的支持是前天才加上的。。。也有可能你需要先`hexo clean`清下缓存再运行
