### ISSUE TITLE
生成静态文件后没有使用主题

### ISSUE THREAD

**Issue by obserthinker** [raytaylorlin/hexo-theme-raytaylorism#16]
在编辑过程中使用hexo server命令时一切正常。在关闭server之后，使用hexo generate生成静态文件后，打开public文件夹下面的index.htm，发现页面没有被主题渲染。情况如图：

![issue](https://cloud.githubusercontent.com/assets/10296215/14135318/6630b37a-f68f-11e5-804a-7db013834eeb.png)

已经按照readme中的进行设置。

**Comment by raytaylorlin** [comment]
`hexo generate`生成出来的public文件夹，直接双击打开index.html是看不到最终效果的，Hexo的机制就是这样的。只要你`hexo server`的预览效果正确，`hexo deploy`到线上之后应该就没问题

**Comment by obserthinker** [comment]
经过尝试的确是这样的。谢谢~

寿寿 <notifications@github.com>于2016年3月30日周三 下午3:56写道：

**Comment by obserthinker** [comment]
试过了的确是这样。这个情况好像没在hexo官方上看到有说明？
谢谢啦~

**Comment by raytaylorlin** [comment]
貌似是没有说明，一般用户都是用`hexo server`、`hexo generate`和`hexo deploy`，通常不会去看public里面的东西吧。。。

PS. 方便说下你的博客地址么？我做个记录

**Comment by obserthinker** [comment]
http://obserthinker.github.io

寿寿 <notifications@github.com>于2016年3月30日周三 下午4:19写道：

**Comment by raytaylorlin** [comment]
你的博文的tag是用逗号分隔的，两个tag被连成了一个，建议md里面写成以下形式：
```
tags:
- Cuda
- Study
```

**Comment by obserthinker** [comment]
哦哦，好的。多谢啦～

寿寿 <notifications@github.com>于2016年3月30日周三 下午8:08写道：
