### ISSUE TITLE
當啟用 終端使用 https 時，mathjax: true 在載入 MathJax.js 顯示非安全連線

### ISSUE THREAD

**Issue by mouson** [raytaylorlin/hexo-theme-raytaylorism#17]
當 Server 端啟用 https 時，如 _config.yml 設定 mathjax: true
會造成在載入頁面時， console 顯示 request an insecure script ，直接被 blocked。

![default](https://cloud.githubusercontent.com/assets/858588/14135443/013d5378-f690-11e5-94d6-d7f6d25db230.png)

PS. 不好意思，一直麻煩您。

**Comment by raytaylorlin** [comment]
[e1c224f](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/e1c224f4545f4f81fda2c499c3a222d65f3b0e72) 已修复

**Comment by mouson** [comment]
感謝。確認已修復。
