### ISSUE TITLE
是否可以新增支援 hexo-generator-search 呢？

### ISSUE THREAD

**Issue by mouson** [raytaylorlin/hexo-theme-raytaylorism#18]
請問，是否可以在 hexo-theme-raytaylorism 裡增加支援如以下連結所提供的 Local Search Engine 呢？

[jQuery-based Local Search Engine for Hexo](http://hahack.com/codes/local-search-engine-for-hexo/)

--
P.S. 我有嘗試著如該文章內容實作，確定它所提供的程式碼是可以運行的。唯須 theme 配合。

**Comment by raytaylorlin** [comment]
我近期也有考虑做search的功能，但从UI设计上来说，我暂时不知道把搜索栏放在哪个地方，你有什么建议吗？

**Comment by mouson** [comment]
以 980px 以上的版面來說，我覺得可以擺在 menu 的右邊或左邊
以 980px 以下的版面來說，可以擺在左邊滑入選單 menu 的最上面或最下面

**Comment by raytaylorlin** [comment]
搜索功能已发布，欢迎试用，使用说明参见[插件-搜索](https://github.com/raytaylorlin/hexo-theme-raytaylorism#插件)
P.S. 思来想去还是用弹框来实现搜索，摆在menu里面实在太丑。。。

**Comment by mouson** [comment]
目前使用起來都還蠻順手的。感謝協助。
