### ISSUE TITLE
使用英文生成的静态文件中，分类的计数量词为中文“篇”

### ISSUE THREAD

**Issue by obserthinker** [raytaylorlin/hexo-theme-raytaylorism#19]
如题。在点击"categories"后在各个分类的后面是"1 篇"等，并未使用英文。

**Comment by raytaylorlin** [comment]
这个问题在[e42af39](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/e42af397893f069257ab7f73a30153fef19e2935)已修复，请更新一下主题

**Comment by obserthinker** [comment]
好的
