### ISSUE TITLE
多行代码显示问题

### ISSUE THREAD

**Issue by ncitycode** [raytaylorlin/hexo-theme-raytaylorism#20]
语法高亮的主题在手机上显示比较乱，上面是数字，下面是代码，但是用手机看你的博客没有这个问题，不知道是不是我配置错误

**Comment by raytaylorlin** [comment]
你是最近才clone这个主题的吗？最新版本的主题应该没这个问题，如果是以前下的可以试着pull更新一下

**Comment by ncitycode** [comment]
好的，我试试




	<
		寿寿> 2016-04-08 20:31:47 wrote:
	
	
	
		
			你是最近才clone这个主题的吗？最新版本的主题应该没这个问题，如果是以前下的可以试着pull更新一下—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by ncitycode** [comment]
并不管用

**Comment by raytaylorlin** [comment]
可以发下你的博客链接我看看吗？

**Comment by ncitycode** [comment]
ncitycode.com

**Comment by raytaylorlin** [comment]
的确是bug，感谢提出，[f6d8268](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/f6d82682644a47b63cfb48c98f94c7e48f61fa3f)已修复
