### ISSUE TITLE
如何修改版面大小？

### ISSUE THREAD

**Issue by AlphaHans** [raytaylorlin/hexo-theme-raytaylorism#21]
我想修改 page页和 文章阅读的宽度大小。感觉现在的页面太窄了。  请问能否告知是在哪个文件中修改？

**Comment by raytaylorlin** [comment]
`themes/raytaylorism/source/css/_base/lib_customize.styl`中4-13行的`.container`和`.main-container`类就是相关设置

**Comment by xxl6097** [comment]
改container的确变宽了，但是目录没一定，文章的目录位置怎么移动
