### ISSUE TITLE
分页Bug

### ISSUE THREAD

**Issue by mysprout** [raytaylorlin/hexo-theme-raytaylorism#24]
我在_config.yml添加了
archive_generator:
  per_page: 0
tag_generator:
  per_page: 0
category_generator:
  per_page: 0
这些代码后，在本地浏览正常分页，上传后，打开网站没有分页，文章显示不全，
删除这些代码，在上传后，就正常了

**Comment by raytaylorlin** [comment]
这几行是禁用掉归档页、tag页和分类目录页的分页功能，应该和文章的分页没有关系的
试下`hexo clean`清下缓存，再`hexo server`看本地正不正常，一般本地正常的话用`hexo deploy -g`重生成发布到线上也是和本地一样的

**Comment by mysprout** [comment]
寿寿，不写这几行有影响吗？我写了这几行上传后的确不行，我每次都上传都clean了的
