### ISSUE TITLE
关闭搜索读书页面的内容

### ISSUE THREAD

**Issue by yeluoqiuzhi** [raytaylorlin/hexo-theme-raytaylorism#26]
我已经把关于和读书页面关闭了，但是搜索还是会搜索读书页面，怎么关闭他？

**Comment by raytaylorlin** [comment]
将`yourblog/_config.yml`中设置如下可仅搜索post：
```
search:
  path: search.xml
  field: post
```
参见：[hexo-generator-search](https://github.com/PaicHyperionDev/hexo-generator-search)

**Comment by yeluoqiuzhi** [comment]
谢谢，已解决哦
