### ISSUE TITLE
文章正文宽度

### ISSUE THREAD

**Issue by xxl6097** [raytaylorlin/hexo-theme-raytaylorism#27]
Hi,请教一个问题，能否把文章的正文宽度调节得更宽一点，我感觉这个宽度太窄了

**Comment by raytaylorlin** [comment]
请参见 #21

**Comment by xxl6097** [comment]
改container的确变宽了，但是目录没一定，文章的目录位置怎么移动

**Comment by xxl6097** [comment]
![image](https://cloud.githubusercontent.com/assets/8170647/15136967/e9d28ad4-16b8-11e6-8b20-f3354b0fbb18.png)

**Comment by raytaylorlin** [comment]
`themes/raytaylorism/source/css/_partial/tablecontents.styl`的`.toc`类，`left`属性决定了toc的位置，原先是定宽700px所以偏移350%，你可以根据你的情况调整此处的CSS
