### ISSUE TITLE
Markdown语法支持问题

### ISSUE THREAD

**Issue by xxl6097** [raytaylorlin/hexo-theme-raytaylorism#28]
在用markdown写文章的时候，比如标题“# 标题”，井号与标题名称之间必须空格，不空格无法识别标题。还有，使用表格的时候，有时候也无法识别

**Comment by raytaylorlin** [comment]
markdown的标题语法就是井号加空格，这和本主题无关，如果你在哪里发现不带空格也能把标题解析出来，那一定不是标准的markdown语法
参见[Markdown syntax header](https://daringfireball.net/projects/markdown/syntax#header)

标准的markdown语法本来也不支持表格，你所使用的表格语法其实是扩展的markdown语法，最常用的是[Github Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)（GFM）
如果要添加表格的话，表格语法复杂手写很容易犯错导致无法识别，建议用类似[Tables Generator](http://www.tablesgenerator.com/markdown_tables)这样的可视化表格编辑工具编辑在粘贴md代码
