### ISSUE TITLE
接入google广告

### ISSUE THREAD

**Issue by xxl6097** [raytaylorlin/hexo-theme-raytaylorism#29]
hey，可否考虑一下把网站接入Google广告，能不能告诉我怎么实现？

**Comment by raytaylorlin** [comment]
这个我不是很清楚，不放google一下找找办法？

**Comment by xxl6097** [comment]
你可以在你的主题里面添加一些广告位出来

**Comment by raytaylorlin** [comment]
不好意思，主题初衷是提供一个干净整洁的阅读环境，不打算添加商业元素。实际上，首页的slider幻灯片就是一个很好的广告载体
