### ISSUE TITLE
关于搜索和社交平台图标的问题

### ISSUE THREAD

**Issue by zhangnew** [raytaylorlin/hexo-theme-raytaylorism#30]
感谢作者提供的这么好的主题。使用过程中有如下问题和建议：

建议：
点击搜索后自动把焦点移动到输入框，这样就不用点击两次了

问题：
1，搜索无效，已经安装和配置，也有 search.xml 文件。
2，社交平台图标使用 http://fontawesome.io/icon/instagram/ 不显示

**Comment by raytaylorlin** [comment]
关于你的建议，我会在下个修订版加入
关于搜索无效的问题，请检查`http://localhost:4000/search.xml`是否能正常显示，再打开控制台看看在输入关键字时，js有没有报错
关于instagram图标，我在`source/_data/link.json`中添加如下行可以正常显示，不知道你是如何配置的，也请看看控制台和hexo有没有报错
```
{
    "social": {
        "instagram": "",
	"rss": "/atom.xml"
    }
}
```
![image](https://cloud.githubusercontent.com/assets/2793052/15267120/79ef4776-19eb-11e6-947c-d97da865ba53.png)

**Comment by zhangnew** [comment]
谢谢，instagram 图标已经解决。

首页打开的时候控制台有如下报错，您的 Blog 也有这个错误。
```
content.js:1 
Uncaught TypeError: Promise.defer is not a function
init @ content.js:1
App @ content.js:1
(anonymous function) @ content.js:1

```

http://localhost:4000/search.xml 可以正常显示，在输入关键字时，js 没有报错，没有任何提示。

**Comment by raytaylorlin** [comment]
> 首页打开的时候控制台有如下报错，您的 Blog 也有这个错误。

你的这个报错代码应该是你的某个浏览器插件所致，和主题无关

关于搜索的问题，我查了很久，最后用Firefox访问``得到如下报错信息，可能是原文有某处带有非UTF8符号导致XML解析错误
```
XML 解析错误：格式不佳
位置：http://github.zhangnew.com/search.xml
行 10274，列 68：<p>2.把wowpc.iso（mac能直接打开ISO）里面文件释放出来修改，然后把修改好的文件全部拖进bootmedia文件夹，只要修改com.apple.Boot.plist为如下：</p>
-------------------------------------------------------------------^
```

**Comment by zhangnew** [comment]
非常感谢，Chrome 中显示您的 search.xml 中也有类似错误，但是我下载后在指定位置没找到非UTF8符号。

```
This page contains the following errors:
error on line 1834 at column 37: Input is not proper UTF-8, indicate encoding !
Bytes: 0xE7 0x94 0xA8 0xE5
Below is a rendering of the page up to the first error.
```

然后我也下载了 Firefox，显示为文章中的某处标签出错了，因为文章是从 Wordpress 导入的，难免格式错误。

**Comment by raytaylorlin** [comment]
这个问题非常奇怪，在Chrome才看得到，其他浏览器不会，但实际上又不影响搜索
既然你的文章是从WP导入的，那很有可能是编码问题，建议你手工转成md再确保保存UTF8编码

**Comment by zhangnew** [comment]
嗯呐，问题解决了，非常感谢！

**Comment by raytaylorlin** [comment]
另外你说的搜索框自动聚焦问题在[f82ab67](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/f82ab67c18c3bccd80259da65840114ac1efe111)添加了，pull下主题即可

**Comment by zhangnew** [comment]
收到，谢谢！
