### ISSUE TITLE
搜索失效

### ISSUE THREAD

**Issue by ankang1943** [raytaylorlin/hexo-theme-raytaylorism#31]
在搜索框里搜索关键字只能出来关联的字,不出来文章

**Comment by raytaylorlin** [comment]
请检查你的`http://localhost:4000/search.xml`是否能正常生成

**Comment by ankang1943** [comment]
谢谢..回家试试

**Comment by ankang1943** [comment]
知道原因了..说是有的编码不是utf8导致的,那么为什么会有这个问题呢?

**Comment by ankang1943** [comment]
找到问题所在了,多谢解惑

**Comment by raytaylorlin** [comment]
我也遇过这个问题，但似乎不影响搜索，你找到的原因是什么？

**Comment by ankang1943** [comment]
生成http://localhost:4000/search.xml报错:Input is not proper UTF-8, indicate encoding !  我之前写markdown用的是Mweb 可能这个编辑器兼容或自动生成了一些非法字,我用别的编辑器打开那个md文件后发现有一个位置有一个红点,其实就是个空格,但是编辑器认为那里有错,我就删了再敲个空格,没有问题,多谢提供思路..
