### ISSUE TITLE
关于&读书页面无法显示

### ISSUE THREAD

**Issue by YumeMichi** [raytaylorlin/hexo-theme-raytaylorism#33]
已经按照[说明](https://github.com/raytaylorlin/hexo-theme-raytaylorism#启用重要)把 _data 和 _md 复制到 source 目录下了，关于和读书页面依然 404

**Comment by KennethYo** [comment]
我这里关于和读书也是404，看 public 上并没有生成。但是文件按照说明上已经配置了。
![2016-06-08 14 15 32](https://cloud.githubusercontent.com/assets/3237000/15884520/b7836e2c-2d83-11e6-9c96-fd8605add4ac.png)
![2016-06-08 14 15 47](https://cloud.githubusercontent.com/assets/3237000/15884522/b9746394-2d83-11e6-90fd-c594ba2f4674.png)

**Comment by YumeMichi** [comment]
是的 当时没看仔细赶忙关了issue哈哈
