### ISSUE TITLE
toc滚动按了没用

### ISSUE THREAD

**Issue by dixyes** [raytaylorlin/hexo-theme-raytaylorism#34]
没有discuss，我就开个issue了
由于Materialize的问题，toc中含unicode字符就会无法点击滚动（估计是他们没想着会有中日韩等语言的使用者）

这么修：
在materialize.min.js（目前项目使用的版本v0.97.6）中
替换

    a('a[href="#'+a(c).attr("id")+'"]').click(function(b){b.preventDefault();var c=a(this.hash).offset().top+1

为

    a('a[href="#'+a(c).attr("id")+'"]').click(function(b){b.preventDefault();var c=a(decodeURIComponent(this.hash)).offset().top+1

效果参见 https://word.donot.help/p/2016-06-14-talk-about-this-blog.html

**Comment by raytaylorlin** [comment]
谢谢，我正愁应该怎么解决这个问题呢，我先把主题里的库给更新一下
不过我之前一直用的都是中文标题，偶然发现标题里面含`/`等这种特殊字符才会导致无法滚动，而且这个问题在不同浏览器下反应还不一样。之前就有人反映safari下均无法点击滚动=。=

**Comment by dixyes** [comment]
这不是你的问题咯 显然Materialize的问题 或许该到他们官网发个issue或者pr？我比较懒就没去 
本着 又不是不能用的精神 把这个通过简单的修改改好就行了
具体错误在这个hash会把tag进行urlencode然而jq不认urlencode之后的utf字符所以要再decode回来就好了
