### ISSUE TITLE
怎样启用小部件

### ISSUE THREAD

**Issue by oec2003** [raytaylorlin/hexo-theme-raytaylorism#4]
1. `_config.yml`配置文件中的`widgets` 能启用吗？
2. `blogrolls` 这个设置了 ，在哪来看可以看到啊？

**Comment by raytaylorlin** [comment]
`widgets`和`blogrolls`在新版v2的主题中已去除，更多配置请参考[README](https://github.com/raytaylorlin/hexo-theme-raytaylorism/blob/master/README.md)
