### ISSUE TITLE
代码框仍然会越界

### ISSUE THREAD

**Issue by zemora** [raytaylorlin/hexo-theme-raytaylorism#40]
首先我确认了我的语法是绝对无误的。但是代码长度达到一定行数以后（10）代码框的行号那一栏比代码栏要长一截。

**Comment by raytaylorlin** [comment]
可以发个线上链接我看看吗？

**Comment by zemora** [comment]
https://zemora.github.io/Lorenz%E5%8A%A8%E7%94%BB/

我还有几个建议：

1. 正文宽度限定为 700px 并不合适：mathjax 在写行内数学公式的时候，一旦行内公式长一点的话，断行就会非常难看。对我这种大量写 latex 的用户来说不能忍。

2. 导航栏的字体开放一个设置的接口。你看看我的例子里面，一旦博客名用了英文，英文字体设置的很难看。

3. 左侧弹出的归档栏还有个人信息栏，真的很难看，希望能用心美化下。

4. 不知道你的 read more 的跳转 bug 修复了没有。

**Comment by zemora** [comment]
不只是我，我看到别人的代码也是一样的问题：[这里](http://wangxianfeng.cn/2016/09/25/%E6%88%91%E5%86%99hexo%E5%8D%9A%E5%AE%A2%E7%9A%84%E4%B9%A0%E6%83%AF/)

**Comment by raytaylorlin** [comment]
[53e06f7](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/53e06f70665943c9c7ea23694ff563c05c7da512) 代码框越界，看看你的代码里面是不是有空行，应该是空行不占位导致，已修复

[cb78734](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/cb7873409bf0e01680620797cb63739fa1b0569f) 非首页READ MORE的bug已修复

**Comment by zemora** [comment]
是 git pull 更新吗

**Comment by raytaylorlin** [comment]
对的

**Comment by zemora** [comment]
我在本地试了一下，好像可以了。

还有一个问题：在关于页面中，在项目的描述的时候，如果描述的字符比较多，超过了方框的范围，就无法显示了。能不能这里制作一个滚动条呢？

**Comment by raytaylorlin** [comment]
OK我记下了，其他建议后续我会跟进，这个问题可以关闭了
