### ISSUE TITLE
markdown代码显示问题

### ISSUE THREAD

**Issue by jiangyixuan** [raytaylorlin/hexo-theme-raytaylorism#41]
确定了markdown语法没问题，在其它主题上解析正常。代码一遇到//注释后面代码就不显示高亮，然后还有代码开始和结尾会显示好几行空行，麻烦作者帮忙看下，地址是：https://jiangyixuan.github.io/2016/08/08/java%20List%E9%9B%86%E5%90%88%EF%BC%88ArrayList%EF%BC%8CLinkedList%EF%BC%8CVertor%EF%BC%8CStack%EF%BC%89/

**Comment by raytaylorlin** [comment]
麻烦提供一下代码段以及前后文若干行的md源码我看看。。。

**Comment by jiangyixuan** [comment]
http://pan.baidu.com/s/1hsyOEfa，麻烦作者了

**Comment by raytaylorlin** [comment]
百度云链接失效了。。。可以麻烦再发一次吗。。。

**Comment by raytaylorlin** [comment]
前后多几行空行的问题，已在[53e06f7](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/53e06f70665943c9c7ea23694ff563c05c7da512) 修复

**Comment by jiangyixuan** [comment]
文章地址：https://jiangyixuan.github.io/2016/09/17/java%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F-%E8%A3%85%E9%A5%B0%E6%A8%A1%E5%BC%8F/ 

markdown文件地址：http://note.youdao.com/noteshare?id=541be186739a80a5c78b61680f0cf536 

// 注释后面代码无法高亮和开头空行。
谢谢作者了



jyx2022@163.com
 
发件人： 寿寿
发送时间： 2016-10-01 23:29
收件人： raytaylorlin/hexo-theme-raytaylorism
抄送： jiangyixuan; Author
主题： Re: [raytaylorlin/hexo-theme-raytaylorism] markdown代码显示问题 (#41)
前后多几行空行的问题，已在53e06f7 修复
