### ISSUE TITLE
"Cannot GET /about/". Page doesn't work

### ISSUE THREAD

**Issue by wzup** [raytaylorlin/hexo-theme-raytaylorism#45]
Why do I see this? How to enable it to work?

![localhost_4000_about_ - google chrome 2016-09-30 13 46 47](https://cloud.githubusercontent.com/assets/3880497/18981864/63ebad02-8714-11e6-8900-b9b799b70187.png)

**Comment by raytaylorlin** [comment]
The theme uses data files and extra layouts, you should:

* Copy `yourblog/themes/raytaylorism/_data` folder to `yourblog/source` folder
* Copy all contents of `yourblog/themes/raytaylorism/_md/` to `yourblog/source`
