### ISSUE TITLE
3.0版本会报错

### ISSUE THREAD

**Issue by nbsky** [raytaylorlin/hexo-theme-raytaylorism#5]
有意向支持吗

**Comment by conjs** [comment]
什么意思？








------------------ 原始邮件 ------------------
发件人: "nbsky";<notifications@github.com>;
发送时间: 2015年3月10日(星期二) 下午2:37
收件人: "raytaylorlin/hexo-theme-raytaylorism"<hexo-theme-raytaylorism@noreply.github.com>; 

主题: [hexo-theme-raytaylorism] 3.0版本会报错 (#5)




有意向支持吗

**Comment by nbsky** [comment]
hexo -v
hexo: 3.0.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l
=======================

hexo g

$ hexo g
ERROR Script load failed: themes\raytaylorism\scripts\model.Post.hook.js
TypeError: Cannot read property 'save' of undefined
    at D:\Program Files (x86)\Git\blog\themes\raytaylorism\scripts\model.Post.ho
ok.js:59:17
    at D:\Program Files (x86)\Git\blog\node_modules\hexo\lib\hexo\index.js:229:1
2

Unhandled rejection ReferenceError: D:\Program Files (x86)\Git\blog\themes\rayta
ylorism\layout\archive.ejs:1
 >> 1| <%- partial('_partial/archive', {pagination: config.archive}) %>

D:\Program Files (x86)\Git\blog\themes\raytaylorism\layout\_partial\archive.ejs:
23
    21| <% } else { %>
    22|     <div class="archive">
 >> 23|         <% for (var i = 0, len = years.length; i < len; i++) { %>
    24|             <div class="archive-year">
    25|                 <a href="./<%= years[i] %>/"><%= years[i] %></a>
    26|                 <div class="sep"></div>


很喜欢您的主题 不知道是不是有更新的计划，我不懂js= =！

**Comment by raytaylorlin** [comment]
@nbsky 抱歉，我在测试hexo 3.0的时候，似乎新版对`{% raw %}`标签的解析方式跟老版的不一样，导致我写的md在3.0中不能被正常解析。所以我现在暂时不打算将主题改为兼容3.0。我使用的hexo版本是2.8.1

**Comment by raytaylorlin** [comment]
@nbsky raytaylorism v2版本现支持hexo 3.1，采用全新的Material Design设计风格，欢迎测试
