### ISSUE TITLE
添加阅读数量

### ISSUE THREAD

**Issue by zhangnew** [raytaylorlin/hexo-theme-raytaylorism#50]
参考这篇文章，有木有兴趣

https://notes.wanghao.work/2015-10-21-%E4%B8%BANexT%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E9%87%8F%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD.html

**Comment by raytaylorlin** [comment]
[67078aa](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/67078aa9e46c5951a1e258f2e22d26fc4cc7d855)已添加，欢迎测试

**Comment by zhangnew** [comment]
不蒜子真的是慢的要死人啊。。。多说要关了，别说你还不知道。。。

**Comment by raytaylorlin** [comment]
我知道，近期在考虑换畅言=。=

**Comment by zhangnew** [comment]
我之前是 Disqus ，打算换网易云跟帖，对网易还是比较放心的。

试了一下 next 主题集成的 leancloud 的 pv 显示，速度完爆不蒜子。

我要是换了 next 主题，你不会打我的，对吧。。。

**Comment by raytaylorlin** [comment]
网易云跟帖看上去好丑啊，不过好像支持导入多说评论=。=
当然不会，主题使用全屏个人爱好

**Comment by zhangnew** [comment]
可以导入多说，不能导入我用的 Disqus 。哭、、、
