### ISSUE TITLE
首页文章链接出现问题

### ISSUE THREAD

**Issue by wrayzh** [raytaylorlin/hexo-theme-raytaylorism#51]
你好，当我测试这一主题的时候，发现首页以及归档页生成的文章链接出现了问题，即http://后面直接跟上了相对路径，缺少了域名部分。原本应该是http://domain.com/date/post.html，变成了http:///date/post.html。我换回默认的landscape主题，没有这一问题。
我查看了一下对应的几个模版文件，发现官方生成链接时使用的函数是<%- url_for(post.path) %>，而这一主题用的是<%- config.root %><%- item.path %>，当我把后者都改成<%- url_for(item.path) %>时问题就解决了。
我总结出的原因是：由于默认config.root是根目录‘/’，这样原代码会在原有相对路径前又加上了‘/'，导致网站不能正确生成文章路径。不知我的分析是否正确，还请多指教。

**Comment by raytaylorlin** [comment]
[02bbb89](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/02bbb89431f586e0f0566f6802d0df44045141d2) 已修复
