### ISSUE TITLE
把json的值设为null，页面就无法正常打开。

### ISSUE THREAD

**Issue by wuchaooooo** [raytaylorlin/hexo-theme-raytaylorism#52]
你好，我按照readme里面说的，比如 我不需要about页面中打赏的图片，我把about.json里面reward的字段改写成"reward":null，可是改了之后about页面就不能正常打开了。有一些页面也是。。我感觉自己没有操作错误啊。

**Comment by raytaylorlin** [comment]
麻烦看一下浏览器控制台以及hexo控制台有没有报什么错
