### ISSUE TITLE
文章菜单问题

### ISSUE THREAD

**Issue by imtianx** [raytaylorlin/hexo-theme-raytaylorism#55]
如果文张中很多小标题，在文章详情页面显示不完整，而且显示到底部了。能否让文章详情也中，菜单页面和文章一样长，这样既可以显示完全，又不至于填充到底部了

**Comment by raytaylorlin** [comment]
如果右侧目录菜单和文章一样长，如何显示完整？

**Comment by coder-pig** [comment]
加入滚动吧，或者折叠，看到这个貌似不错的样子：

**Comment by coder-pig** [comment]
https://notes.wanghao.work/2015-10-21-%E4%B8%BANexT%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E9%87%8F%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD.html

**Comment by raytaylorlin** [comment]
@coder-pig 很不错的参考，后期会考虑加上

**Comment by codingyuan** [comment]
@raytaylorlin 我在pullrequest加上了一个标题栏滚动的功能 效果可参考http://mobnav.qunar.com/2016/09/12/qav/
