### ISSUE TITLE
页面导航栏语言设置问题

### ISSUE THREAD

**Issue by Shineee** [raytaylorlin/hexo-theme-raytaylorism#57]
/blog/_config.yml 已经配置为language: en，但是导航栏的文字却是繁体字，看一下
http://diaobee.com/

**Comment by raytaylorlin** [comment]
导航栏是哪里麻烦截个图我看下。。。

**Comment by Shineee** [comment]
![qq 20161209155121](https://cloud.githubusercontent.com/assets/2569939/21041651/667d9a18-be27-11e6-8ab7-52605d653de0.png)
就是这个位置，不过现在好像没有了，我是用hexo clean，hexo generate之后就可能会出现。

**Comment by raytaylorlin** [comment]
一般来说，不需要每次都clean的，显示不正常可能是缓存问题

**Comment by Shineee** [comment]
好的
