### ISSUE TITLE
about页面内容无法修改

### ISSUE THREAD

**Issue by Simon0000** [raytaylorlin/hexo-theme-raytaylorism#62]
按照作者的建议，把yourblog/source/_data/about.json 文件进行了修改，只修改了字段里面的值，把原来位于public文件夹中的about目录删除，重新执行"hexo g"生成about文件夹。运行之后，发现生成的index还是作者给的木板，页面内容并没有改变。只有通过source/about/index.md生成的内容生效了。不知道是什么原因，求作者解答！

**Comment by Simon0000** [comment]
另外，追问一下作者，请问搜索功能是如何做的？求告知！

**Comment by raytaylorlin** [comment]
建议把整个public删了再重新generate一次，hexo自动生成的东西很多，只删掉一个文件夹不一定能更新到对应的功能。

搜索功能参照[hexo-generator-search](https://github.com/PaicHyperionDev/hexo-generator-search)这个插件
