### ISSUE TITLE
代码高亮相关问题

### ISSUE THREAD

**Issue by LooEv** [raytaylorlin/hexo-theme-raytaylorism#65]
你好，我遇到两个关于代码高亮的问题，我以为是我使用的 node.js 和 Hexo 的版本问题，于是我在另一台电脑上试着重新安装最新的 node.js，然后 hexo s -g，查看效果，问题依然存在。问题是这样的：
1、代码高亮区域与其后面的段落间隔过大
2、代码高亮对注释的解析不够好
http://threehao.com/2016/08/22/Github%20Pages%20+%20Hexo/ 从这个链接文章中的第一段代码高亮可以明显看出来这两个问题，我贴一段我的 md内容：

```
### 环境配置，安装所需软件
需要用到的软件有：
  * [Node.js](https://nodejs.org/en/download/ "下载Node.js")
  * [git](https://git-scm.com/download/ "下载git")

### 安装Hexo

```bash
$ npm install hexo-cli -g
$ cd the_path_you_wanna_build_blog
$ hexo init <your_blog_name> # your_blog_name 可以缺省
$ npm install
$ hexo g # 或者hexo generate
$ hexo s # 或者hexo server，可以在http://localhost:4000/ 查看
```      到这儿结束
```

不知道是不是我的代码写法有问题，至于间隔过大的问题，我真的不知道是什么原因了，会是我的站点配置问题吗。可是我测试了一下其他主题，我反映的这两个问题竟然都不存在了，，，，大神，看你的了！

**补充说明：我试着用其他方法解决，关闭了hexo自带的代码高亮功能，手动引入 highlight.js，发现问题解决了。**

**Comment by raytaylorlin** [comment]
试了下你的md片段，的确有这两个问题。

1. 注意md支持两种代码格式语法，一种是代码段前后加`````，会带行号（解析成figure和table），而主题中table的确会带有margin-bottom，这个是可以修的。另一种是代码段前空4个空格，不带行号
2. 我拿同一段代码用两种不同的代码格式语法测了一下，发现解析出来的HTML根本就不一样，这才导致用带行号的写法对注释解析不够好，这个问题暂时无解，后面再慢慢研究看如何解决。。。

**Comment by LooEv** [comment]
好的，感谢解答
