### ISSUE TITLE
首页没有文章简介

### ISSUE THREAD

**Issue by itvincent-git** [raytaylorlin/hexo-theme-raytaylorism#68]
请问下如何让首页出现文章的简介呢，用了你的主题我的首页只有文章的标题，没有你的博客里的效果

**Comment by raytaylorlin** [comment]
这是hexo处理md的机制，你可以理解为hexo的文章分为摘要（Excerpts）和正文，在你的md中以“”分隔即可，这个符号前自动解析为摘要，符号后为正文

**Comment by zhiqiang21** [comment]
大神您好，“在你的md中以“”分隔即可”  指的是下面这样使用么

![image](https://cloud.githubusercontent.com/assets/3990411/22617899/884a7ff2-eb0a-11e6-88c9-69c7775c43e6.png)

**Comment by raytaylorlin** [comment]
不好意思，尖括号被屏蔽掉了，应该是以以下这个为分隔

`<!-- more -->`
