### ISSUE TITLE
图片题注

### ISSUE THREAD

**Issue by weigq** [raytaylorlin/hexo-theme-raytaylorism#72]
为什么不能显示图片的题注：
`![image](iamges/avatar.png "avatar")`
markdown的标准语法里面不是可以给图片加题注吗？

**Comment by raytaylorlin** [comment]
所谓的题注是指`<img>`标签里面的`title`属性，表现为下图
![default](https://cloud.githubusercontent.com/assets/2793052/25552414/e2050c1c-2ccb-11e7-8ba9-9f2176cdee0f.png)
