### ISSUE TITLE
滑动文章页面到底部然后滑回顶部，右侧的目录显示错误

### ISSUE THREAD

**Issue by zekunyan** [raytaylorlin/hexo-theme-raytaylorism#76]
链接：[http://tutuge.me/2016/06/19/translation-why-objcmsgsend-must-be-written-in-assembly/](http://tutuge.me/2016/06/19/translation-why-objcmsgsend-must-be-written-in-assembly/)

![image](https://cloud.githubusercontent.com/assets/5687881/23331706/fc442ce0-fba5-11e6-80ca-608cb3fd1b45.png)

**Comment by zekunyan** [comment]
升级了下好了=。=

**Comment by Rayuu** [comment]
请问是要重新升级一下这个主题还是升级hexo呢？我也遇到和你一样的情况。

**Comment by zekunyan** [comment]
@Rayuu 用最新版， hexo clean 然后 hexo g重新生成
