### ISSUE TITLE
代码段里一行太长，换行时行数显示错误

### ISSUE THREAD

**Issue by zekunyan** [raytaylorlin/hexo-theme-raytaylorism#8]
如图：
![image](http://ww3.sinaimg.cn/large/0060lm7Tgw1f23euqhyizj312i07c76d.jpg)

建议：
不换行，改为可以横向滑动

**Comment by raytaylorlin** [comment]
[c4fa4c1](https://github.com/raytaylorlin/hexo-theme-raytaylorism/commit/c4fa4c130971c11c99cdb7cf6bbd42da8782b880) 已修复
