### ISSUE TITLE
请问怎么设置背景图片

### ISSUE THREAD

**Issue by neozhaoliang** [raytaylorlin/hexo-theme-raytaylorism#82]
我想给页面增加一个背景图片（默认的都是空白嘛），这个应该怎么修改呢?

**Comment by raytaylorlin** [comment]
主题不支持这个特殊功能，这种特殊需求你可以自行修改主题的模板来实现，这个需要你会一点前端的知识才行
大概思路是给`layout/layout.ejs`的main标签加个CSS类，然后去`source/css/_base/layout.styl`加一点CSS即可
