### ISSUE TITLE
请问如何修改评论系统

### ISSUE THREAD

**Issue by meishadevs** [raytaylorlin/hexo-theme-raytaylorism#84]
我在使用raytaylorism主题搭建博客的时候，当集成好多说评论系统后提示“多说使用将于2017年6月1日到期,请尽快迁移,详见duoshuo.com”，我想换成其他的评论系统，在网上找到了一个友言评论系统，请问我该如何修改，才能将多说评论系统换成友言评论系统。

**Comment by raytaylorlin** [comment]
`layout/_partial/plugin/comment.ejs`里面增加评论插件代码，并在`_config.yml`中配置。经过对市面多款评论插件一番调研，后续我会将多说替换成网易云跟帖

**Comment by meishadevs** [comment]
谢谢

**Comment by meishadevs** [comment]
还有一个问题，插入代码后，当一行代码的长度超过代码展示区的宽度的时候，水平方向的滚动条与代码展示区有一段距离，请问如何去掉那段距离。
存在这个问题的博客[http://meishadevs.com/blog/开发中的一些小知识点](http://meishadevs.com/blog/开发中的一些小知识点)

**Comment by raytaylorlin** [comment]
滚动条样式是浏览器内置的。。。估计没法改。。。
