### ISSUE TITLE
关于修改slider.json以及link.json,about.json

### ISSUE THREAD

**Issue by sivanWu0222** [raytaylorlin/hexo-theme-raytaylorism#85]
自己clone之后，修改了slider.json文件，换了图片路径以及正副标题和对齐方式，link,json和about.json也是修改了，但是hexo s之后还是原来的效果，没有更改，不知道如何改变呢

**Comment by raytaylorlin** [comment]
试下`hexo clean`清理下，以及清理浏览器缓存

**Comment by sivanWu0222** [comment]
clean和清理缓存都不行，自己改了about和reading页面的layout，效果出来了，之前没有加上相应的layout，但是首页的slider.json自己只在slider.json中改了链接，效果还是不出来，看了几遍文档，不知道还需要改哪里
