### ISSUE TITLE
手机版的网页云跟帖的评论框挡住了右下角的浮悬按钮

### ISSUE THREAD

**Issue by YxxY** [raytaylorlin/hexo-theme-raytaylorism#89]
浮悬按钮默认沉底，评论框刚好也在底部，按钮几乎完全被覆盖，如没看明白可以晚点上图

**Comment by YxxY** [comment]
![cover](http://opxo4bto2.bkt.clouddn.com/cover.png)
如上图所示

**Comment by YxxY** [comment]
一不小心自己找到原因了，这里自问自答下吧。。需要去网易云跟帖设置，这里文字说明下，进后台管理后点_获取代码_，然后_皮肤设置_，拉到最下面的**Wap跟贴样式选择**，选_固定位置_，然后保存。上面提到的两个问题就都解决了。

**Comment by raytaylorlin** [comment]
确实有问题，非常感谢提出解决方案！
