### ISSUE TITLE
文章详情页右侧列表，文件树缩进格式问题

### ISSUE THREAD

**Issue by githubao** [raytaylorlin/hexo-theme-raytaylorism#90]
缩进不对，也并不能确定是不是我的markdown格式有问题。
有时间烦请看一下，感谢~

![qq 20170604092954](https://cloud.githubusercontent.com/assets/8923601/26758159/ac82ea6a-4908-11e7-866e-ba3536383a45.png)

**Comment by raytaylorlin** [comment]
文章的目录是根据md文件里面的h1...h6标签来划分的，需要你根据文章的结构定义好一级标题、二级标题......

**Comment by githubao** [comment]
@raytaylorlin 你好，可能是我问题描述的不够清楚。如果有时间，烦请看一下这个[链接](https://githubao.github.io/2017/09/16/201709/post20170916_%E9%A9%AC%E6%8B%89%E6%9D%BE%E8%B5%9B%E4%BA%8B/)。我认为自己的md的文档格式写的是没错的，但是右侧的导航树缩进有问题。不胜感谢。

**Comment by raytaylorlin** [comment]
看了一下链接，可能是用了4级标题后接6级标题导致解析有误。建议markdown遵循标题分级原则，从一级开始分标题，例如：
```
# 最想跑的

## TOP1

## TOP2

# 国际马拉松

# 其他金牌
```

**Comment by githubao** [comment]
@raytaylorlin 嗯嗯，的确是这样，非常感谢~~~
