### ISSUE TITLE
接下来换什么评论

### ISSUE THREAD

**Issue by imtianx** [raytaylorlin/hexo-theme-raytaylorism#92]
网易云跟帖8.1号要关了，接下来打算换什么评论

**Comment by YxxY** [comment]
want to ask the same question...

**Comment by raytaylorlin** [comment]
很头痛，国产只剩下搜狐的畅言了吧=。=

**Comment by LooEv** [comment]
哎，很尴尬，评论系统一个接着一个关闭

**Comment by Wangzhike** [comment]
最近有个[Gitalk](https://github.com/gitalk/gitalk/blob/master/readme-cn.md)还不错，可以考虑下。

**Comment by raytaylorlin** [comment]
不折腾了，我自己的博客准备换disqus了（主题原来就支持），本主题不打算再扩展其他第三方工具了，用户需要的话自己扩展就行了

**Comment by Wangzhike** [comment]
恩恩，理解理解。还是得感谢作者您的这个主题，很棒！

**Comment by raytaylorlin** [comment]
感谢支持哈
