### ISSUE TITLE
请问首页文章列表的文章如何显示预览和阅读全文按钮

### ISSUE THREAD

**Issue by Wangzhike** [raytaylorlin/hexo-theme-raytaylorism#94]
![default](https://user-images.githubusercontent.com/12167883/28856440-a5cac7d8-7775-11e7-990d-d210ad856a38.PNG)

如图所示，只有文章标题，无法显示正文预览以及作者博客的阅读全文按钮，请问该如何设置？

**Comment by Wangzhike** [comment]
哦，百度了下，要在文章里面截止预览的地方加入`<!--more-->`

**Comment by raytaylorlin** [comment]
> 哦，百度了下，要在文章里面截止预览的地方加入
对的
