### ISSUE TITLE
博客顶部标签栏，如何删除或增加项目？

### ISSUE THREAD

**Issue by fengyu-song** [raytaylorlin/hexo-theme-raytaylorism#97]
博主您好：
我近期刚刚使用您创作的该主题，在使用期间
博客顶部有一条/home/archives/categories/reading/about/等标签
我想删掉其中的reading栏，如何删除呢？或者说如何改变其名称呢？
首页滑动栏的图片最好的匹配像素是多少呢？
希望得到您的回复
万分感谢

**Comment by raytaylorlin** [comment]
顶部菜单配置在主题的`_config.yml`里面，你一看就明白了
slider图片建议2:1的图片，参考高度为400，即800*400
