### ISSUE TITLE
生成的代码没有样式

### ISSUE THREAD

**Issue by cdkd321** [raytaylorlin/hexo-theme-raytaylorism#98]
代码完全没有样式的。请博主看一下：
项目地址：https://github.com/cdkd321/blogs
[网站](https://cdkd321.github.io/blogs/)

**Comment by raytaylorlin** [comment]
麻烦把你的代码那部分的md贴一下。。。
不过单看你的网站的文章，那些菜谱看起来不是应该使用代码的地方，代码样式都是针对真正的编程语言的

**Comment by cdkd321** [comment]
额，我换了一个主题。觉得简单的主题还是好些。不过还是谢了。
