### ISSUE TITLE
md文件配置

### ISSUE THREAD

**Issue by fengxianzai** [raytaylorlin/hexo-theme-raytaylorism#99]
写文章时，md文件上的配置是怎么配置的？几个参数不知道啊
![image](https://user-images.githubusercontent.com/26562244/31313956-4aec60a8-ac25-11e7-9b03-2b5342cf14b1.png)

**Comment by raytaylorlin** [comment]
参见[《Hexo文档-写作》](https://hexo.io/zh-cn/docs/writing.html)
